/**
 * Definições de Permissões Padrão
 * Centraliza todas as permissões padrão por tipo e nível de acesso
 */

// Definir permissões padrão por tipo e nível de acesso
const PERMISSOES_PADRAO = {
  administrador: {
    I: {
      usuarios: { visualizar: true, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: false, editar: false, excluir: false },
      filiais: { visualizar: true, criar: false, editar: false, excluir: false },
      rotas_nutricionistas: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades_escolares: { visualizar: true, criar: false, editar: false, excluir: false },
      produtos_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_medida: { visualizar: true, criar: false, editar: false, excluir: false },
      centros_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      receitas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_receitas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_pratos: { visualizar: true, criar: false, editar: false, excluir: false },
      pratos: { visualizar: true, criar: false, editar: false, excluir: false },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    II: {
      usuarios: { visualizar: true, criar: true, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: true, editar: true, excluir: false },
      filiais: { visualizar: true, criar: true, editar: true, excluir: false },
      rotas_nutricionistas: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades_escolares: { visualizar: true, criar: true, editar: true, excluir: false },
      produtos_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_medida: { visualizar: true, criar: false, editar: false, excluir: false },
      centros_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      tipos_receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      tipos_pratos: { visualizar: true, criar: true, editar: true, excluir: false },
      pratos: { visualizar: true, criar: true, editar: true, excluir: false },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    III: {
      usuarios: { visualizar: true, criar: true, editar: true, excluir: true },
      fornecedores: { visualizar: true, criar: true, editar: true, excluir: true },
      filiais: { visualizar: true, criar: true, editar: true, excluir: true },
      rotas_nutricionistas: { visualizar: true, criar: true, editar: true, excluir: true },
      unidades_escolares: { visualizar: true, criar: true, editar: true, excluir: true },
      produtos_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_medida: { visualizar: true, criar: false, editar: false, excluir: false },
      centros_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: true },
      tipos_receitas: { visualizar: true, criar: true, editar: true, excluir: true },
      tipos_pratos: { visualizar: true, criar: true, editar: true, excluir: true },
      pratos: { visualizar: true, criar: true, editar: true, excluir: true },
      permissoes: { visualizar: true, criar: true, editar: true, excluir: true }
    }
  },
  coordenador: {
    I: {
      usuarios: { visualizar: true, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: false, editar: false, excluir: false },
      filiais: { visualizar: true, criar: false, editar: false, excluir: false },
      rotas_nutricionistas: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades_escolares: { visualizar: true, criar: false, editar: false, excluir: false },
      produtos_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_medida: { visualizar: true, criar: false, editar: false, excluir: false },
      centros_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      receitas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_receitas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_pratos: { visualizar: true, criar: false, editar: false, excluir: false },
      pratos: { visualizar: true, criar: false, editar: false, excluir: false },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    II: {
      usuarios: { visualizar: true, criar: true, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: true, editar: true, excluir: false },
      filiais: { visualizar: true, criar: true, editar: true, excluir: false },
      rotas_nutricionistas: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades_escolares: { visualizar: true, criar: true, editar: true, excluir: false },
      produtos_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_medida: { visualizar: true, criar: false, editar: false, excluir: false },
      centros_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      tipos_receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      tipos_pratos: { visualizar: true, criar: true, editar: true, excluir: false },
      pratos: { visualizar: true, criar: true, editar: true, excluir: false },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    III: {
      usuarios: { visualizar: true, criar: true, editar: true, excluir: false },
      fornecedores: { visualizar: true, criar: true, editar: true, excluir: true },
      filiais: { visualizar: true, criar: true, editar: true, excluir: true },
      rotas_nutricionistas: { visualizar: true, criar: true, editar: true, excluir: true },
      unidades_escolares: { visualizar: true, criar: true, editar: true, excluir: true },
      produtos_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_medida: { visualizar: true, criar: false, editar: false, excluir: false },
      centros_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      tipos_receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      tipos_pratos: { visualizar: true, criar: true, editar: true, excluir: false },
      pratos: { visualizar: true, criar: true, editar: true, excluir: false },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    }
  },
  administrativo: {
    I: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: false, editar: false, excluir: false },
      filiais: { visualizar: true, criar: false, editar: false, excluir: false },
      rotas_nutricionistas: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades_escolares: { visualizar: true, criar: false, editar: false, excluir: false },
      produtos_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_medida: { visualizar: true, criar: false, editar: false, excluir: false },
      centros_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      receitas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_receitas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_pratos: { visualizar: true, criar: false, editar: false, excluir: false },
      pratos: { visualizar: true, criar: false, editar: false, excluir: false },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    II: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: true, editar: false, excluir: false },
      filiais: { visualizar: true, criar: true, editar: false, excluir: false },
      rotas_nutricionistas: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades_escolares: { visualizar: true, criar: true, editar: false, excluir: false },
      produtos_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_medida: { visualizar: true, criar: false, editar: false, excluir: false },
      centros_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      receitas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_receitas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_pratos: { visualizar: true, criar: false, editar: false, excluir: false },
      pratos: { visualizar: true, criar: false, editar: false, excluir: false },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    III: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: true, editar: true, excluir: false },
      filiais: { visualizar: true, criar: true, editar: true, excluir: false },
      rotas_nutricionistas: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades_escolares: { visualizar: true, criar: true, editar: true, excluir: false },
      produtos_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_medida: { visualizar: true, criar: false, editar: false, excluir: false },
      centros_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      tipos_receitas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_pratos: { visualizar: true, criar: false, editar: false, excluir: false },
      pratos: { visualizar: true, criar: true, editar: true, excluir: false },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    }
  },
  gerente: {
    I: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: false, editar: false, excluir: false },
      filiais: { visualizar: true, criar: false, editar: false, excluir: false },
      rotas_nutricionistas: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades_escolares: { visualizar: true, criar: false, editar: false, excluir: false },
      produtos_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_medida: { visualizar: true, criar: false, editar: false, excluir: false },
      centros_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      receitas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_receitas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_pratos: { visualizar: true, criar: false, editar: false, excluir: false },
      pratos: { visualizar: true, criar: false, editar: false, excluir: false },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    II: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: true, editar: true, excluir: false },
      filiais: { visualizar: true, criar: true, editar: true, excluir: false },
      rotas_nutricionistas: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades_escolares: { visualizar: true, criar: true, editar: true, excluir: false },
      produtos_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_medida: { visualizar: true, criar: false, editar: false, excluir: false },
      centros_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      tipos_receitas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_pratos: { visualizar: true, criar: false, editar: false, excluir: false },
      pratos: { visualizar: true, criar: true, editar: true, excluir: false },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    III: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: true, editar: true, excluir: true },
      filiais: { visualizar: true, criar: true, editar: true, excluir: true },
      rotas_nutricionistas: { visualizar: true, criar: true, editar: true, excluir: true },
      unidades_escolares: { visualizar: true, criar: true, editar: true, excluir: true },
      produtos_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_medida: { visualizar: true, criar: false, editar: false, excluir: false },
      centros_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      tipos_receitas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_pratos: { visualizar: true, criar: false, editar: false, excluir: false },
      pratos: { visualizar: true, criar: true, editar: true, excluir: false },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    }
  },
  supervisor: {
    I: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: false, editar: false, excluir: false },
      filiais: { visualizar: true, criar: false, editar: false, excluir: false },
      rotas_nutricionistas: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades_escolares: { visualizar: true, criar: false, editar: false, excluir: false },
      produtos_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_medida: { visualizar: true, criar: false, editar: false, excluir: false },
      centros_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      receitas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_receitas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_pratos: { visualizar: true, criar: false, editar: false, excluir: false },
      pratos: { visualizar: true, criar: false, editar: false, excluir: false },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    II: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: true, editar: true, excluir: false },
      filiais: { visualizar: true, criar: true, editar: true, excluir: false },
      rotas_nutricionistas: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades_escolares: { visualizar: true, criar: true, editar: true, excluir: false },
      produtos_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_medida: { visualizar: true, criar: false, editar: false, excluir: false },
      centros_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      tipos_receitas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_pratos: { visualizar: true, criar: false, editar: false, excluir: false },
      pratos: { visualizar: true, criar: true, editar: true, excluir: false },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    III: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: true, editar: true, excluir: true },
      filiais: { visualizar: true, criar: true, editar: true, excluir: true },
      rotas_nutricionistas: { visualizar: true, criar: true, editar: true, excluir: true },
      unidades_escolares: { visualizar: true, criar: true, editar: true, excluir: true },
      produtos_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_medida: { visualizar: true, criar: false, editar: false, excluir: false },
      centros_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      tipos_receitas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_pratos: { visualizar: true, criar: false, editar: false, excluir: false },
      pratos: { visualizar: true, criar: true, editar: true, excluir: false },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    }
  },
  nutricionista: {
    I: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: false, criar: false, editar: false, excluir: false },
      filiais: { visualizar: false, criar: false, editar: false, excluir: false },
      rotas_nutricionistas: { visualizar: false, criar: false, editar: false, excluir: false },
      unidades_escolares: { visualizar: true, criar: false, editar: false, excluir: false },
      produtos_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_medida: { visualizar: true, criar: false, editar: false, excluir: false },
      centros_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      receitas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_receitas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_pratos: { visualizar: true, criar: false, editar: false, excluir: false },
      pratos: { visualizar: true, criar: false, editar: false, excluir: false },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    II: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: false, criar: false, editar: false, excluir: false },
      filiais: { visualizar: false, criar: false, editar: false, excluir: false },
      rotas_nutricionistas: { visualizar: false, criar: false, editar: false, excluir: false },
      unidades_escolares: { visualizar: true, criar: true, editar: true, excluir: false },
      produtos_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_medida: { visualizar: true, criar: false, editar: false, excluir: false },
      centros_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      tipos_receitas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_pratos: { visualizar: true, criar: false, editar: false, excluir: false },
      pratos: { visualizar: true, criar: true, editar: true, excluir: false },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    III: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: false, criar: false, editar: false, excluir: false },
      filiais: { visualizar: false, criar: false, editar: false, excluir: false },
      rotas_nutricionistas: { visualizar: false, criar: false, editar: false, excluir: false },
      unidades_escolares: { visualizar: true, criar: true, editar: true, excluir: true },
      produtos_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_medida: { visualizar: true, criar: false, editar: false, excluir: false },
      centros_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: true },
      tipos_receitas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_pratos: { visualizar: true, criar: false, editar: false, excluir: false },
      pratos: { visualizar: true, criar: true, editar: true, excluir: true },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    }
  }
};

// Lista de todas as telas disponíveis no sistema
const TODAS_TELAS = [
  'usuarios',
  'fornecedores',
  'filiais',
  'unidades_escolares',
  'produtos_origem',
  'produtos_genericos',
  'produtos_comerciais',
  'almoxarifados',
  'centros_custo',
  'unidades_medida',
  'grupos',
  'subgrupos',
  'classes',
  'receitas',
  'tipos_receitas',
  'tipos_pratos',
  'pratos',
  'permissoes'
];

// Tipos de acesso disponíveis
const TIPOS_ACESSO = [
  { valor: 'administrador', descricao: 'Administrador' },
  { valor: 'coordenador', descricao: 'Coordenador' },
  { valor: 'administrativo', descricao: 'Administrativo' },
  { valor: 'gerente', descricao: 'Gerente' },
  { valor: 'supervisor', descricao: 'Supervisor' },
  { valor: 'nutricionista', descricao: 'Nutricionista' }
];

// Níveis de acesso disponíveis
const NIVEIS_ACESSO = [
  { valor: 'I', descricao: 'Nível I - Básico' },
  { valor: 'II', descricao: 'Nível II - Intermediário' },
  { valor: 'III', descricao: 'Nível III - Avançado' }
];

// Lista de telas com descrições
const TELAS_COM_DESCRICOES = [
  { nome: 'usuarios', descricao: 'Gerenciamento de Usuários' },
  { nome: 'fornecedores', descricao: 'Gerenciamento de Fornecedores' },
  { nome: 'filiais', descricao: 'Gerenciamento de Filiais' },
  { nome: 'unidades_escolares', descricao: 'Gerenciamento de Unidades Escolares' },
  { nome: 'produtos_origem', descricao: 'Consulta de Produtos Origem' },
  { nome: 'produtos_genericos', descricao: 'Consulta de Produtos Genéricos' },
  { nome: 'produtos_comerciais', descricao: 'Consulta de Produtos Comerciais' },
  { nome: 'almoxarifados', descricao: 'Consulta de Almoxarifados' },
  { nome: 'centros_custo', descricao: 'Consulta de Centros de Custo' },
  { nome: 'unidades_medida', descricao: 'Consulta de Unidades de Medida' },
  { nome: 'grupos', descricao: 'Consulta de Grupos' },
  { nome: 'subgrupos', descricao: 'Consulta de Subgrupos' },
  { nome: 'classes', descricao: 'Consulta de Classes' },
  { nome: 'receitas', descricao: 'Cadastro de Receitas' },
  { nome: 'tipos_receitas', descricao: 'Cadastro de Tipos de Receitas' },
  { nome: 'tipos_pratos', descricao: 'Cadastro de Tipos de Pratos' },
  { nome: 'pratos', descricao: 'Cadastro de Pratos' },
  { nome: 'permissoes', descricao: 'Gerenciamento de Permissões' }
];

module.exports = {
  PERMISSOES_PADRAO,
  TODAS_TELAS,
  TIPOS_ACESSO,
  NIVEIS_ACESSO,
  TELAS_COM_DESCRICOES
};