version: '3.8'

# Rede interna para comunicação segura entre sistemas
networks:
  terceirize_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# Serviços compartilhados (banco de dados, etc.)
services:
  # API Gateway (opcional - para usar com nginx)
  api-gateway:
    image: nginx:alpine
    container_name: terceirize_api_gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./api-gateway/logs:/var/log/nginx
    networks:
      - terceirize_network
    profiles:
      - gateway

  # Banco de dados MySQL compartilhado
  mysql:
    image: mysql:8.0
    container_name: terceirize_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-terceirize_db}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - terceirize_network
    profiles:
      - database

volumes:
  mysql_data:
    driver: local
