version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: foods_mysql_dev
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: foods_db
      MYSQL_USER: foods_user
      MYSQL_PASSWORD: foods123456
    volumes:
      - mysql_data:/var/lib/mysql
      - ../database/init:/docker-entrypoint-initdb.d
    networks:
      - foods_dev_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s

volumes:
  mysql_data:

networks:
  foods_dev_network:
    driver: bridge
