services:
  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cotacao_frontend
    # Expondo porta 80 para produção
    expose:
      - "80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://cotacao_backend:5000
      - REACT_APP_MAIN_API_URL=http://foods_backend:3001/api
      # Configuração para subcaminho
      - PUBLIC_URL=/cotacao
      - REACT_APP_BASE_PATH=/cotacao
    depends_on:
      - backend
    networks:
      - terceirize_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Backend Node.js
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cotacao_backend
    # Removendo exposição direta de porta - será acessado via proxy
    expose:
      - "5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=terceirize_mysql
      - DB_USER=foods_user
      - DB_PASSWORD=foods123456
      - DB_NAME=cotacao_db
      - DB_PORT=3306
      - JWT_SECRET=foods_jwt_secret_key_2024
    networks:
      - terceirize_network
    restart: unless-stopped
    depends_on: []
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  terceirize_network:
    external: true 