version: '3.8'

services:
  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://82.29.57.43:5001
    depends_on:
      - backend
    networks:
      - app-network

  # Backend Node.js
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=82.29.57.43
      - DB_USER=foods_user
      - DB_PASSWORD=foods123456
      - DB_NAME=foods_db
      - DB_PORT=3306
      - JWT_SECRET=foods_jwt_secret_key_2024
    networks:
      - app-network
    restart: unless-stopped

  # MySQL removido - usando o banco principal do sistema foods

  # phpMyAdmin removido - usando o do sistema principal na porta 8080

networks:
  app-network:
    driver: bridge 