/**
 * Definições de Permissões Padrão
 * Centraliza todas as permissões padrão por tipo e nível de acesso
 */

// Definir permissões padrão por tipo e nível de acesso
const PERMISSOES_PADRAO = {
  administrador: {
    I: {
      usuarios: { visualizar: true, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: false, editar: false, excluir: false },
      clientes: { visualizar: true, criar: false, editar: false, excluir: false },
      filiais: { visualizar: true, criar: false, editar: false, excluir: false },
      centro_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      almoxarifado: { visualizar: true, criar: false, editar: false, excluir: false },
      rotas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipo_rota: { visualizar: true, criar: false, editar: false, excluir: false },
      produtos: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_escolares: { visualizar: true, criar: false, editar: false, excluir: false },
      marcas: { visualizar: true, criar: false, editar: false, excluir: false },
      veiculos: { visualizar: true, criar: false, editar: false, excluir: false },
      motoristas: { visualizar: true, criar: false, editar: false, excluir: false },
      ajudantes: { visualizar: true, criar: false, editar: false, excluir: false },
      cotacao: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_generico: { visualizar: true, criar: false, editar: false, excluir: false },
      intolerancias: { visualizar: true, criar: false, editar: false, excluir: false },
      patrimonios: { visualizar: true, criar: false, editar: false, excluir: false, movimentar: true },
      rotas_nutricionistas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_cardapio: { visualizar: true, criar: false, editar: false, excluir: false },
      periodos_refeicao: { visualizar: true, criar: false, editar: false, excluir: false },
      periodicidade: { visualizar: true, criar: false, editar: false, excluir: false },
      faturamento: { visualizar: true, criar: true, editar: true, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      necessidades_merenda: { visualizar: true, criar: true, editar: true, excluir: false },
      plano_amostragem: { visualizar: true, criar: true, editar: true, excluir: false },
      relatorio_inspecao: { visualizar: true, criar: true, editar: true, excluir: false },
      solicitacoes_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      calendario: { visualizar: true, criar: true, editar: true, excluir: false },
      formas_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      prazos_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      pedidos_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      notas_fiscais: { visualizar: true, criar: true, editar: true, excluir: false },
      pdf_templates: { visualizar: true, criar: true, editar: true, excluir: true },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
      
    },
    II: {
      usuarios: { visualizar: true, criar: true, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: true, editar: true, excluir: false },
      clientes: { visualizar: true, criar: true, editar: true, excluir: false },
      filiais: { visualizar: true, criar: true, editar: true, excluir: false },
      centro_custo: { visualizar: true, criar: true, editar: true, excluir: false },
      almoxarifado: { visualizar: true, criar: true, editar: true, excluir: false },
      rotas: { visualizar: true, criar: true, editar: true, excluir: false },
      tipo_rota: { visualizar: true, criar: true, editar: true, excluir: false },
      produtos: { visualizar: true, criar: true, editar: true, excluir: false },
      grupos: { visualizar: true, criar: true, editar: true, excluir: false },
      subgrupos: { visualizar: true, criar: true, editar: true, excluir: false },
      classes: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades_escolares: { visualizar: true, criar: true, editar: true, excluir: false },
      marcas: { visualizar: true, criar: true, editar: true, excluir: false },
      veiculos: { visualizar: true, criar: true, editar: true, excluir: false },
      motoristas: { visualizar: true, criar: true, editar: true, excluir: false },
      ajudantes: { visualizar: true, criar: true, editar: true, excluir: false },
      cotacao: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_generico: { visualizar: true, criar: false, editar: false, excluir: false },
      intolerancias: { visualizar: true, criar: false, editar: false, excluir: false }, 
      patrimonios: { visualizar: true, criar: false, editar: false, excluir: false, movimentar: true },
      rotas_nutricionistas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_cardapio: { visualizar: true, criar: false, editar: false, excluir: false },
      periodos_refeicao: { visualizar: true, criar: false, editar: false, excluir: false },
      periodicidade: { visualizar: true, criar: true, editar: true, excluir: false },
      faturamento: { visualizar: true, criar: true, editar: true, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      necessidades_merenda: { visualizar: true, criar: true, editar: true, excluir: false },
      plano_amostragem: { visualizar: true, criar: true, editar: true, excluir: false },
      relatorio_inspecao: { visualizar: true, criar: true, editar: true, excluir: false },
      solicitacoes_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      calendario: { visualizar: true, criar: true, editar: true, excluir: false },
      formas_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      prazos_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      pedidos_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      notas_fiscais: { visualizar: true, criar: true, editar: true, excluir: false },
      pdf_templates: { visualizar: true, criar: true, editar: true, excluir: true },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    III: {
      usuarios: { visualizar: true, criar: true, editar: true, excluir: true },
      fornecedores: { visualizar: true, criar: true, editar: true, excluir: true },
      clientes: { visualizar: true, criar: true, editar: true, excluir: true },
      filiais: { visualizar: true, criar: true, editar: true, excluir: true },
      centro_custo: { visualizar: true, criar: true, editar: true, excluir: true },
      almoxarifado: { visualizar: true, criar: true, editar: true, excluir: true },
      rotas: { visualizar: true, criar: true, editar: true, excluir: true },
      tipo_rota: { visualizar: true, criar: true, editar: true, excluir: true },
      produtos: { visualizar: true, criar: true, editar: true, excluir: true },
      grupos: { visualizar: true, criar: true, editar: true, excluir: true },
      subgrupos: { visualizar: true, criar: true, editar: true, excluir: true },
      classes: { visualizar: true, criar: true, editar: true, excluir: true },
      unidades: { visualizar: true, criar: true, editar: true, excluir: true },
      unidades_escolares: { visualizar: true, criar: true, editar: true, excluir: true },
      marcas: { visualizar: true, criar: true, editar: true, excluir: true },
      veiculos: { visualizar: true, criar: true, editar: true, excluir: true },
      motoristas: { visualizar: true, criar: true, editar: true, excluir: true },
      ajudantes: { visualizar: true, criar: true, editar: true, excluir: true },
      cotacao: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_generico: { visualizar: true, criar: false, editar: false, excluir: false },
      intolerancias: { visualizar: true, criar: false, editar: false, excluir: false },   
      patrimonios: { visualizar: true, criar: false, editar: false, excluir: false, movimentar: true },
      rotas_nutricionistas: { visualizar: true, criar: true, editar: true, excluir: true },
      tipos_cardapio: { visualizar: true, criar: true, editar: true, excluir: true },
      periodos_refeicao: { visualizar: true, criar: true, editar: true, excluir: true },
      periodicidade: { visualizar: true, criar: true, editar: true, excluir: true },
      faturamento: { visualizar: true, criar: true, editar: true, excluir: true },
      receitas: { visualizar: true, criar: true, editar: true, excluir: true },
      necessidades_merenda: { visualizar: true, criar: true, editar: true, excluir: true },
      plano_amostragem: { visualizar: true, criar: true, editar: true, excluir: true },
      relatorio_inspecao: { visualizar: true, criar: true, editar: true, excluir: true },
      solicitacoes_compras: { visualizar: true, criar: true, editar: true, excluir: true },
      calendario: { visualizar: true, criar: true, editar: true, excluir: true },
      formas_pagamento: { visualizar: true, criar: true, editar: true, excluir: true },
      pedidos_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      notas_fiscais: { visualizar: true, criar: true, editar: true, excluir: false },
      permissoes: { visualizar: true, criar: true, editar: true, excluir: true }
    }
  },
  coordenador: {
    I: {
      usuarios: { visualizar: true, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: false, editar: false, excluir: false },
      clientes: { visualizar: true, criar: false, editar: false, excluir: false },
      filiais: { visualizar: true, criar: false, editar: false, excluir: false },
      centro_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      almoxarifado: { visualizar: true, criar: false, editar: false, excluir: false },
      rotas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipo_rota: { visualizar: true, criar: false, editar: false, excluir: false },
      produtos: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_escolares: { visualizar: true, criar: false, editar: false, excluir: false },
      marcas: { visualizar: true, criar: false, editar: false, excluir: false },
      veiculos: { visualizar: true, criar: false, editar: false, excluir: false },
      motoristas: { visualizar: true, criar: false, editar: false, excluir: false },
      ajudantes: { visualizar: true, criar: false, editar: false, excluir: false },
      cotacao: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_generico: { visualizar: true, criar: false, editar: false, excluir: false },
      intolerancias: { visualizar: true, criar: false, editar: false, excluir: false },
      patrimonios: { visualizar: true, criar: false, editar: false, excluir: false, movimentar: true },
      rotas_nutricionistas: { visualizar: true, criar: true, editar: true, excluir: true },
      tipos_cardapio: { visualizar: true, criar: true, editar: true, excluir: true },
      periodos_refeicao: { visualizar: true, criar: true, editar: true, excluir: true },
      periodicidade: { visualizar: true, criar: true, editar: true, excluir: true },
      faturamento: { visualizar: true, criar: true, editar: true, excluir: true },
      receitas: { visualizar: true, criar: true, editar: true, excluir: true },
      necessidades_merenda: { visualizar: true, criar: true, editar: true, excluir: true },
      plano_amostragem: { visualizar: true, criar: true, editar: true, excluir: true },
      relatorio_inspecao: { visualizar: true, criar: true, editar: true, excluir: true },
      solicitacoes_compras: { visualizar: true, criar: true, editar: true, excluir: true },
      calendario: { visualizar: true, criar: true, editar: true, excluir: true },
      formas_pagamento: { visualizar: true, criar: true, editar: true, excluir: true },
      pedidos_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      notas_fiscais: { visualizar: true, criar: true, editar: true, excluir: false },
      pdf_templates: { visualizar: true, criar: true, editar: true, excluir: true },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    II: {
      usuarios: { visualizar: true, criar: true, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: true, editar: true, excluir: false },
      clientes: { visualizar: true, criar: true, editar: true, excluir: false },
      filiais: { visualizar: true, criar: true, editar: true, excluir: false },
      centro_custo: { visualizar: true, criar: true, editar: true, excluir: false },
      almoxarifado: { visualizar: true, criar: true, editar: true, excluir: false },
      rotas: { visualizar: true, criar: true, editar: true, excluir: false },
      tipo_rota: { visualizar: true, criar: true, editar: true, excluir: false },
      produtos: { visualizar: true, criar: true, editar: true, excluir: false },
      grupos: { visualizar: true, criar: true, editar: true, excluir: false },
      subgrupos: { visualizar: true, criar: true, editar: true, excluir: false },
      classes: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades_escolares: { visualizar: true, criar: true, editar: true, excluir: false },
      marcas: { visualizar: true, criar: true, editar: true, excluir: false },
      veiculos: { visualizar: true, criar: true, editar: true, excluir: false },
      motoristas: { visualizar: true, criar: true, editar: true, excluir: false },
      ajudantes: { visualizar: true, criar: true, editar: true, excluir: false },
      cotacao: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_generico: { visualizar: true, criar: false, editar: false, excluir: false },
      intolerancias: { visualizar: true, criar: true, editar: true, excluir: false },
      patrimonios: { visualizar: true, criar: true, editar: true, excluir: false, movimentar: true },
      rotas_nutricionistas: { visualizar: true, criar: true, editar: true, excluir: false },
      tipos_cardapio: { visualizar: true, criar: true, editar: true, excluir: false },
      periodos_refeicao: { visualizar: true, criar: true, editar: true, excluir: false },
      periodicidade: { visualizar: true, criar: true, editar: true, excluir: false },
      faturamento: { visualizar: true, criar: true, editar: true, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      necessidades_merenda: { visualizar: true, criar: true, editar: true, excluir: false },
      plano_amostragem: { visualizar: true, criar: true, editar: true, excluir: false },
      relatorio_inspecao: { visualizar: true, criar: true, editar: true, excluir: false },
      solicitacoes_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      calendario: { visualizar: true, criar: true, editar: true, excluir: false },
      formas_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      prazos_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      pedidos_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      notas_fiscais: { visualizar: true, criar: true, editar: true, excluir: false },
      pdf_templates: { visualizar: true, criar: true, editar: true, excluir: true },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    III: {
      usuarios: { visualizar: true, criar: true, editar: true, excluir: false },
      fornecedores: { visualizar: true, criar: true, editar: true, excluir: true },
      clientes: { visualizar: true, criar: true, editar: true, excluir: true },
      filiais: { visualizar: true, criar: true, editar: true, excluir: true },
      centro_custo: { visualizar: true, criar: true, editar: true, excluir: true },
      almoxarifado: { visualizar: true, criar: true, editar: true, excluir: true },
      rotas: { visualizar: true, criar: true, editar: true, excluir: true },
      tipo_rota: { visualizar: true, criar: true, editar: true, excluir: true },
      produtos: { visualizar: true, criar: true, editar: true, excluir: true },
      grupos: { visualizar: true, criar: true, editar: true, excluir: true },
      subgrupos: { visualizar: true, criar: true, editar: true, excluir: true },
      classes: { visualizar: true, criar: true, editar: true, excluir: true },
      unidades: { visualizar: true, criar: true, editar: true, excluir: true },
      unidades_escolares: { visualizar: true, criar: true, editar: true, excluir: true },
      marcas: { visualizar: true, criar: true, editar: true, excluir: true },
      veiculos: { visualizar: true, criar: true, editar: true, excluir: true },
      motoristas: { visualizar: true, criar: true, editar: true, excluir: true },
      ajudantes: { visualizar: true, criar: true, editar: true, excluir: true },
      cotacao: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_generico: { visualizar: true, criar: false, editar: false, excluir: false },
      intolerancias: { visualizar: true, criar: false, editar: false, excluir: false },
      patrimonios: { visualizar: true, criar: false, editar: false, excluir: false, movimentar: true },
      rotas_nutricionistas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_cardapio: { visualizar: true, criar: false, editar: false, excluir: false },
      periodos_refeicao: { visualizar: true, criar: false, editar: false, excluir: false },
      periodicidade: { visualizar: true, criar: false, editar: false, excluir: false },
      faturamento: { visualizar: true, criar: true, editar: true, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      necessidades_merenda: { visualizar: true, criar: true, editar: true, excluir: false },
      plano_amostragem: { visualizar: true, criar: true, editar: true, excluir: false },
      relatorio_inspecao: { visualizar: true, criar: true, editar: true, excluir: false },
      solicitacoes_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      calendario: { visualizar: true, criar: true, editar: true, excluir: false },
      formas_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      prazos_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      pedidos_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      notas_fiscais: { visualizar: true, criar: true, editar: true, excluir: false },
      pdf_templates: { visualizar: true, criar: true, editar: true, excluir: true },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    }
  },
  administrativo: {
    I: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: false, editar: false, excluir: false },
      clientes: { visualizar: true, criar: false, editar: false, excluir: false },
      filiais: { visualizar: true, criar: false, editar: false, excluir: false },
      centro_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      almoxarifado: { visualizar: true, criar: false, editar: false, excluir: false },
      rotas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipo_rota: { visualizar: true, criar: false, editar: false, excluir: false },
      produtos: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_escolares: { visualizar: true, criar: false, editar: false, excluir: false },
      marcas: { visualizar: true, criar: false, editar: false, excluir: false },
      veiculos: { visualizar: true, criar: false, editar: false, excluir: false },
      motoristas: { visualizar: true, criar: false, editar: false, excluir: false },
      ajudantes: { visualizar: true, criar: false, editar: false, excluir: false },
      cotacao: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_generico: { visualizar: true, criar: false, editar: false, excluir: false },
      intolerancias: { visualizar: true, criar: false, editar: false, excluir: false },
      patrimonios: { visualizar: true, criar: false, editar: false, excluir: false, movimentar: true },
      rotas_nutricionistas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_cardapio: { visualizar: true, criar: false, editar: false, excluir: false },
      periodos_refeicao: { visualizar: true, criar: false, editar: false, excluir: false },
      periodicidade: { visualizar: true, criar: false, editar: false, excluir: false },
      faturamento: { visualizar: true, criar: true, editar: true, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      necessidades_merenda: { visualizar: true, criar: true, editar: true, excluir: false },
      plano_amostragem: { visualizar: true, criar: true, editar: true, excluir: false },
      relatorio_inspecao: { visualizar: true, criar: true, editar: true, excluir: false },
      solicitacoes_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      calendario: { visualizar: true, criar: true, editar: true, excluir: false },
      formas_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      prazos_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      pedidos_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      notas_fiscais: { visualizar: true, criar: true, editar: true, excluir: false },
      pdf_templates: { visualizar: true, criar: true, editar: true, excluir: true },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    II: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: true, editar: false, excluir: false },
      clientes: { visualizar: true, criar: true, editar: false, excluir: false },
      filiais: { visualizar: true, criar: true, editar: false, excluir: false },
      centro_custo: { visualizar: true, criar: true, editar: false, excluir: false },
      rotas: { visualizar: true, criar: true, editar: false, excluir: false },
      tipo_rota: { visualizar: true, criar: true, editar: false, excluir: false },
      produtos: { visualizar: true, criar: true, editar: false, excluir: false },
      grupos: { visualizar: true, criar: true, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: true, editar: false, excluir: false },
      classes: { visualizar: true, criar: true, editar: false, excluir: false },
      unidades: { visualizar: true, criar: true, editar: false, excluir: false },
      unidades_escolares: { visualizar: true, criar: true, editar: false, excluir: false },
      marcas: { visualizar: true, criar: true, editar: false, excluir: false },
      veiculos: { visualizar: true, criar: true, editar: false, excluir: false },
      motoristas: { visualizar: true, criar: true, editar: false, excluir: false },
      ajudantes: { visualizar: true, criar: true, editar: false, excluir: false },
      cotacao: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_origem: { visualizar: true, criar: true, editar: true, excluir: false },
      produto_generico: { visualizar: true, criar: true, editar: true, excluir: false },
      intolerancias: { visualizar: true, criar: true, editar: true, excluir: false },
      patrimonios: { visualizar: true, criar: true, editar: true, excluir: false, movimentar: true },
      rotas_nutricionistas: { visualizar: true, criar: true, editar: true, excluir: false },
      tipos_cardapio: { visualizar: true, criar: true, editar: true, excluir: false },
      periodos_refeicao: { visualizar: true, criar: true, editar: true, excluir: false },
      periodicidade: { visualizar: true, criar: true, editar: true, excluir: false },
      faturamento: { visualizar: true, criar: true, editar: true, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      necessidades_merenda: { visualizar: true, criar: true, editar: true, excluir: false },
      plano_amostragem: { visualizar: true, criar: true, editar: true, excluir: false },
      relatorio_inspecao: { visualizar: true, criar: true, editar: true, excluir: false },
      solicitacoes_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      calendario: { visualizar: true, criar: true, editar: true, excluir: false },
      formas_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      prazos_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      pedidos_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      notas_fiscais: { visualizar: true, criar: true, editar: true, excluir: false },
      pdf_templates: { visualizar: true, criar: true, editar: true, excluir: true },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    III: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: true, editar: true, excluir: false },
      clientes: { visualizar: true, criar: true, editar: true, excluir: false },
      filiais: { visualizar: true, criar: true, editar: true, excluir: false },
      centro_custo: { visualizar: true, criar: true, editar: true, excluir: false },
      almoxarifado: { visualizar: true, criar: true, editar: true, excluir: false },
      rotas: { visualizar: true, criar: true, editar: true, excluir: false },
      tipo_rota: { visualizar: true, criar: true, editar: true, excluir: false },
      produtos: { visualizar: true, criar: true, editar: true, excluir: false },
      grupos: { visualizar: true, criar: true, editar: true, excluir: false },
      subgrupos: { visualizar: true, criar: true, editar: true, excluir: false },
      classes: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades_escolares: { visualizar: true, criar: true, editar: true, excluir: false },
      marcas: { visualizar: true, criar: true, editar: true, excluir: false },
      veiculos: { visualizar: true, criar: true, editar: true, excluir: false },
      motoristas: { visualizar: true, criar: true, editar: true, excluir: false },
      ajudantes: { visualizar: true, criar: true, editar: true, excluir: false },     
      cotacao: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_origem: { visualizar: true, criar: true, editar: true, excluir: false },
      produto_generico: { visualizar: true, criar: true, editar: true, excluir: false },
      intolerancias: { visualizar: true, criar: true, editar: true, excluir: false },
      patrimonios: { visualizar: true, criar: true, editar: true, excluir: false, movimentar: true },
      rotas_nutricionistas: { visualizar: true, criar: true, editar: true, excluir: false },
      tipos_cardapio: { visualizar: true, criar: true, editar: true, excluir: false },
      periodos_refeicao: { visualizar: true, criar: true, editar: true, excluir: false },
      periodicidade: { visualizar: true, criar: true, editar: true, excluir: false },
      faturamento: { visualizar: true, criar: true, editar: true, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      necessidades_merenda: { visualizar: true, criar: true, editar: true, excluir: false },
      plano_amostragem: { visualizar: true, criar: true, editar: true, excluir: false },
      relatorio_inspecao: { visualizar: true, criar: true, editar: true, excluir: false },
      solicitacoes_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      calendario: { visualizar: true, criar: true, editar: true, excluir: false },
      formas_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      prazos_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      pedidos_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      notas_fiscais: { visualizar: true, criar: true, editar: true, excluir: false },
      pdf_templates: { visualizar: true, criar: true, editar: true, excluir: true },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    }
  },
  gerente: {
    I: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: false, editar: false, excluir: false },
      clientes: { visualizar: true, criar: false, editar: false, excluir: false },
      filiais: { visualizar: true, criar: false, editar: false, excluir: false },
      centro_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      almoxarifado: { visualizar: true, criar: false, editar: false, excluir: false },
      rotas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipo_rota: { visualizar: true, criar: false, editar: false, excluir: false },
      produtos: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_escolares: { visualizar: true, criar: false, editar: false, excluir: false },
      marcas: { visualizar: true, criar: false, editar: false, excluir: false },
      veiculos: { visualizar: true, criar: false, editar: false, excluir: false },
      motoristas: { visualizar: true, criar: false, editar: false, excluir: false },
      ajudantes: { visualizar: true, criar: false, editar: false, excluir: false },
      cotacao: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_generico: { visualizar: true, criar: false, editar: false, excluir: false },
      intolerancias: { visualizar: true, criar: false, editar: false, excluir: false },
      patrimonios: { visualizar: true, criar: false, editar: false, excluir: false, movimentar: true },
      rotas_nutricionistas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_cardapio: { visualizar: true, criar: false, editar: false, excluir: false },
      periodos_refeicao: { visualizar: true, criar: false, editar: false, excluir: false },
      periodicidade: { visualizar: true, criar: false, editar: false, excluir: false },
      faturamento: { visualizar: true, criar: true, editar: true, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      necessidades_merenda: { visualizar: true, criar: true, editar: true, excluir: false },
      plano_amostragem: { visualizar: true, criar: true, editar: true, excluir: false },
      relatorio_inspecao: { visualizar: true, criar: true, editar: true, excluir: false },
      solicitacoes_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      calendario: { visualizar: true, criar: true, editar: true, excluir: false },
      formas_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      prazos_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      pedidos_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      notas_fiscais: { visualizar: true, criar: true, editar: true, excluir: false },
      pdf_templates: { visualizar: true, criar: true, editar: true, excluir: true },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    II: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: true, editar: true, excluir: false },
      clientes: { visualizar: true, criar: true, editar: true, excluir: false },
      filiais: { visualizar: true, criar: true, editar: true, excluir: false },
      centro_custo: { visualizar: true, criar: true, editar: true, excluir: false },
      almoxarifado: { visualizar: true, criar: true, editar: true, excluir: false },
      rotas: { visualizar: true, criar: true, editar: true, excluir: false },
      tipo_rota: { visualizar: true, criar: true, editar: true, excluir: false },
      produtos: { visualizar: true, criar: true, editar: true, excluir: false },
      grupos: { visualizar: true, criar: true, editar: true, excluir: false },
      subgrupos: { visualizar: true, criar: true, editar: true, excluir: false },
      classes: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades_escolares: { visualizar: true, criar: true, editar: true, excluir: false },
      marcas: { visualizar: true, criar: true, editar: true, excluir: false },
      veiculos: { visualizar: true, criar: true, editar: true, excluir: false },
      motoristas: { visualizar: true, criar: true, editar: true, excluir: false },
      ajudantes: { visualizar: true, criar: true, editar: true, excluir: false },
      cotacao: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_generico: { visualizar: true, criar: false, editar: false, excluir: false },
      intolerancias: { visualizar: true, criar: false, editar: false, excluir: false },
      patrimonios: { visualizar: true, criar: false, editar: false, excluir: false, movimentar: true },
      rotas_nutricionistas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_cardapio: { visualizar: true, criar: false, editar: false, excluir: false },
      periodos_refeicao: { visualizar: true, criar: false, editar: false, excluir: false },
      periodicidade: { visualizar: true, criar: false, editar: false, excluir: false },
      faturamento: { visualizar: true, criar: true, editar: true, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      necessidades_merenda: { visualizar: true, criar: true, editar: true, excluir: false },
      plano_amostragem: { visualizar: true, criar: true, editar: true, excluir: false },
      relatorio_inspecao: { visualizar: true, criar: true, editar: true, excluir: false },
      solicitacoes_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      calendario: { visualizar: true, criar: true, editar: true, excluir: false },
      formas_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      prazos_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      pedidos_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      notas_fiscais: { visualizar: true, criar: true, editar: true, excluir: false },
      pdf_templates: { visualizar: true, criar: true, editar: true, excluir: true },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    III: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: true, editar: true, excluir: true },
      clientes: { visualizar: true, criar: true, editar: true, excluir: true },
      filiais: { visualizar: true, criar: true, editar: true, excluir: true },
      centro_custo: { visualizar: true, criar: true, editar: true, excluir: true },
      almoxarifado: { visualizar: true, criar: true, editar: true, excluir: true },
      rotas: { visualizar: true, criar: true, editar: true, excluir: true },
      tipo_rota: { visualizar: true, criar: true, editar: true, excluir: true },
      produtos: { visualizar: true, criar: true, editar: true, excluir: true },
      grupos: { visualizar: true, criar: true, editar: true, excluir: true },
      subgrupos: { visualizar: true, criar: true, editar: true, excluir: true },
      classes: { visualizar: true, criar: true, editar: true, excluir: true },
      unidades: { visualizar: true, criar: true, editar: true, excluir: true },
      unidades_escolares: { visualizar: true, criar: true, editar: true, excluir: true },
      marcas: { visualizar: true, criar: true, editar: true, excluir: true },
      veiculos: { visualizar: true, criar: true, editar: true, excluir: true },
      motoristas: { visualizar: true, criar: true, editar: true, excluir: true },
      ajudantes: { visualizar: true, criar: true, editar: true, excluir: true },
      cotacao: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_generico: { visualizar: true, criar: false, editar: false, excluir: false },
      intolerancias: { visualizar: true, criar: false, editar: false, excluir: false },
      patrimonios: { visualizar: true, criar: false, editar: false, excluir: false, movimentar: true },
      rotas_nutricionistas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_cardapio: { visualizar: true, criar: false, editar: false, excluir: false },
      periodos_refeicao: { visualizar: true, criar: false, editar: false, excluir: false },
      periodicidade: { visualizar: true, criar: false, editar: false, excluir: false },
      faturamento: { visualizar: true, criar: true, editar: true, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      necessidades_merenda: { visualizar: true, criar: true, editar: true, excluir: false },
      plano_amostragem: { visualizar: true, criar: true, editar: true, excluir: false },
      relatorio_inspecao: { visualizar: true, criar: true, editar: true, excluir: false },
      solicitacoes_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      calendario: { visualizar: true, criar: true, editar: true, excluir: false },
      formas_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      prazos_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      pedidos_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      notas_fiscais: { visualizar: true, criar: true, editar: true, excluir: false },
      pdf_templates: { visualizar: true, criar: true, editar: true, excluir: true },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    }
  },
  supervisor: {
    I: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: false, editar: false, excluir: false },
      clientes: { visualizar: true, criar: false, editar: false, excluir: false },
      filiais: { visualizar: true, criar: false, editar: false, excluir: false },
      centro_custo: { visualizar: true, criar: false, editar: false, excluir: false },
      almoxarifado: { visualizar: true, criar: false, editar: false, excluir: false },
      rotas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipo_rota: { visualizar: true, criar: false, editar: false, excluir: false },
      produtos: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_escolares: { visualizar: true, criar: false, editar: false, excluir: false },
      marcas: { visualizar: true, criar: false, editar: false, excluir: false },
      veiculos: { visualizar: true, criar: false, editar: false, excluir: false },
      motoristas: { visualizar: true, criar: false, editar: false, excluir: false },
      ajudantes: { visualizar: true, criar: false, editar: false, excluir: false },
      cotacao: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_generico: { visualizar: true, criar: false, editar: false, excluir: false },
      intolerancias: { visualizar: true, criar: false, editar: false, excluir: false },
      patrimonios: { visualizar: true, criar: false, editar: false, excluir: false, movimentar: true },
      rotas_nutricionistas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_cardapio: { visualizar: true, criar: false, editar: false, excluir: false },
      periodos_refeicao: { visualizar: true, criar: false, editar: false, excluir: false },
      periodicidade: { visualizar: true, criar: false, editar: false, excluir: false },
      faturamento: { visualizar: true, criar: true, editar: true, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      necessidades_merenda: { visualizar: true, criar: true, editar: true, excluir: false },
      plano_amostragem: { visualizar: true, criar: true, editar: true, excluir: false },
      relatorio_inspecao: { visualizar: true, criar: true, editar: true, excluir: false },
      solicitacoes_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      calendario: { visualizar: true, criar: true, editar: true, excluir: false },
      formas_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      prazos_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      pedidos_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      notas_fiscais: { visualizar: true, criar: true, editar: true, excluir: false },
      pdf_templates: { visualizar: true, criar: true, editar: true, excluir: true },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    II: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: true, editar: true, excluir: false },
      clientes: { visualizar: true, criar: true, editar: true, excluir: false },
      filiais: { visualizar: true, criar: true, editar: true, excluir: false },
      centro_custo: { visualizar: true, criar: true, editar: true, excluir: false },
      almoxarifado: { visualizar: true, criar: true, editar: true, excluir: false },
      rotas: { visualizar: true, criar: true, editar: true, excluir: false },
      tipo_rota: { visualizar: true, criar: true, editar: true, excluir: false },
      produtos: { visualizar: true, criar: true, editar: true, excluir: false },
      grupos: { visualizar: true, criar: true, editar: true, excluir: false },
      subgrupos: { visualizar: true, criar: true, editar: true, excluir: false },
      classes: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades_escolares: { visualizar: true, criar: true, editar: true, excluir: false },
      marcas: { visualizar: true, criar: true, editar: true, excluir: false },
      veiculos: { visualizar: true, criar: true, editar: true, excluir: false },
      motoristas: { visualizar: true, criar: true, editar: true, excluir: false },
      ajudantes: { visualizar: true, criar: true, editar: true, excluir: false },
      cotacao: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_generico: { visualizar: true, criar: false, editar: false, excluir: false },
      intolerancias: { visualizar: true, criar: false, editar: false, excluir: false },
      patrimonios: { visualizar: true, criar: false, editar: false, excluir: false, movimentar: true },
      rotas_nutricionistas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_cardapio: { visualizar: true, criar: false, editar: false, excluir: false },
      periodos_refeicao: { visualizar: true, criar: false, editar: false, excluir: false },
      periodicidade: { visualizar: true, criar: false, editar: false, excluir: false },
      faturamento: { visualizar: true, criar: true, editar: true, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      necessidades_merenda: { visualizar: true, criar: true, editar: true, excluir: false },
      plano_amostragem: { visualizar: true, criar: true, editar: true, excluir: false },
      relatorio_inspecao: { visualizar: true, criar: true, editar: true, excluir: false },
      solicitacoes_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      calendario: { visualizar: true, criar: true, editar: true, excluir: false },
      formas_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      prazos_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      pedidos_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      notas_fiscais: { visualizar: true, criar: true, editar: true, excluir: false },
      pdf_templates: { visualizar: true, criar: true, editar: true, excluir: true },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    III: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: true, criar: true, editar: true, excluir: true },
      clientes: { visualizar: true, criar: true, editar: true, excluir: true },
      filiais: { visualizar: true, criar: true, editar: true, excluir: true },
      centro_custo: { visualizar: true, criar: true, editar: true, excluir: true },
      almoxarifado: { visualizar: true, criar: true, editar: true, excluir: true },
      rotas: { visualizar: true, criar: true, editar: true, excluir: true },
      tipo_rota: { visualizar: true, criar: true, editar: true, excluir: true },
      produtos: { visualizar: true, criar: true, editar: true, excluir: true },
      grupos: { visualizar: true, criar: true, editar: true, excluir: true },
      subgrupos: { visualizar: true, criar: true, editar: true, excluir: true },
      classes: { visualizar: true, criar: true, editar: true, excluir: true },
      unidades: { visualizar: true, criar: true, editar: true, excluir: true },
      unidades_escolares: { visualizar: true, criar: true, editar: true, excluir: true },
      marcas: { visualizar: true, criar: true, editar: true, excluir: true },
      veiculos: { visualizar: true, criar: true, editar: true, excluir: true },
      motoristas: { visualizar: true, criar: true, editar: true, excluir: true },
      ajudantes: { visualizar: true, criar: true, editar: true, excluir: true },
      cotacao: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_generico: { visualizar: true, criar: false, editar: false, excluir: false },
      intolerancias: { visualizar: true, criar: false, editar: false, excluir: false },
      patrimonios: { visualizar: true, criar: false, editar: false, excluir: false, movimentar: true },
      rotas_nutricionistas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_cardapio: { visualizar: true, criar: false, editar: false, excluir: false },
      periodos_refeicao: { visualizar: true, criar: false, editar: false, excluir: false },
      periodicidade: { visualizar: true, criar: false, editar: false, excluir: false },
      faturamento: { visualizar: true, criar: true, editar: true, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      necessidades_merenda: { visualizar: true, criar: true, editar: true, excluir: false },
      plano_amostragem: { visualizar: true, criar: true, editar: true, excluir: false },
      relatorio_inspecao: { visualizar: true, criar: true, editar: true, excluir: false },
      solicitacoes_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      calendario: { visualizar: true, criar: true, editar: true, excluir: false },
      formas_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      prazos_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      pedidos_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      notas_fiscais: { visualizar: true, criar: true, editar: true, excluir: false },
      pdf_templates: { visualizar: true, criar: true, editar: true, excluir: true },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    }
  },
  nutricionista: {
    I: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: false, criar: false, editar: false, excluir: false },
      clientes: { visualizar: false, criar: false, editar: false, excluir: false },
      filiais: { visualizar: false, criar: false, editar: false, excluir: false },
      centro_custo: { visualizar: false, criar: false, editar: false, excluir: false },
      almoxarifado: { visualizar: false, criar: false, editar: false, excluir: false },
      rotas: { visualizar: false, criar: false, editar: false, excluir: false },
      tipo_rota: { visualizar: false, criar: false, editar: false, excluir: false },
      produtos: { visualizar: true, criar: false, editar: false, excluir: false },
      grupos: { visualizar: true, criar: false, editar: false, excluir: false },
      subgrupos: { visualizar: true, criar: false, editar: false, excluir: false },
      classes: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades: { visualizar: true, criar: false, editar: false, excluir: false },
      unidades_escolares: { visualizar: true, criar: false, editar: false, excluir: false },
      marcas: { visualizar: true, criar: false, editar: false, excluir: false },
      veiculos: { visualizar: false, criar: false, editar: false, excluir: false },
      motoristas: { visualizar: false, criar: false, editar: false, excluir: false },
      ajudantes: { visualizar: false, criar: false, editar: false, excluir: false },
      cotacao: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_origem: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_generico: { visualizar: true, criar: false, editar: false, excluir: false },
      intolerancias: { visualizar: true, criar: true, editar: true, excluir: false },
      patrimonios: { visualizar: false, criar: false, editar: false, excluir: false, movimentar: false },
      rotas_nutricionistas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_cardapio: { visualizar: true, criar: false, editar: false, excluir: false },
      periodos_refeicao: { visualizar: true, criar: false, editar: false, excluir: false },
      periodicidade: { visualizar: true, criar: false, editar: false, excluir: false },
      faturamento: { visualizar: true, criar: true, editar: true, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      necessidades_merenda: { visualizar: true, criar: true, editar: true, excluir: false },
      plano_amostragem: { visualizar: true, criar: true, editar: true, excluir: false },
      relatorio_inspecao: { visualizar: true, criar: true, editar: true, excluir: false },
      solicitacoes_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      calendario: { visualizar: true, criar: true, editar: true, excluir: false },
      formas_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      prazos_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      pedidos_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      notas_fiscais: { visualizar: true, criar: true, editar: true, excluir: false },
      pdf_templates: { visualizar: true, criar: true, editar: true, excluir: true },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    II: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: false, criar: false, editar: false, excluir: false },
      clientes: { visualizar: false, criar: false, editar: false, excluir: false },
      filiais: { visualizar: false, criar: false, editar: false, excluir: false },
      centro_custo: { visualizar: false, criar: false, editar: false, excluir: false },
      almoxarifado: { visualizar: false, criar: false, editar: false, excluir: false },
      rotas: { visualizar: false, criar: false, editar: false, excluir: false },
      tipo_rota: { visualizar: false, criar: false, editar: false, excluir: false },
      produtos: { visualizar: true, criar: true, editar: true, excluir: false },
      grupos: { visualizar: true, criar: true, editar: true, excluir: false },
      subgrupos: { visualizar: true, criar: true, editar: true, excluir: false },
      classes: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades: { visualizar: true, criar: true, editar: true, excluir: false },
      unidades_escolares: { visualizar: true, criar: true, editar: true, excluir: false },
      marcas: { visualizar: true, criar: true, editar: true, excluir: false },
      veiculos: { visualizar: false, criar: false, editar: false, excluir: false },
      motoristas: { visualizar: false, criar: false, editar: false, excluir: false },
      ajudantes: { visualizar: false, criar: false, editar: false, excluir: false },
      cotacao: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_origem: { visualizar: true, criar: true, editar: true, excluir: false },
      produto_generico: { visualizar: true, criar: true, editar: true, excluir: false },
      intolerancias: { visualizar: true, criar: true, editar: true, excluir: true },
      patrimonios: { visualizar: false, criar: false, editar: false, excluir: false, movimentar: false },
      rotas_nutricionistas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_cardapio: { visualizar: true, criar: false, editar: false, excluir: false },
      periodos_refeicao: { visualizar: true, criar: false, editar: false, excluir: false },
      periodicidade: { visualizar: true, criar: false, editar: false, excluir: false },
      faturamento: { visualizar: true, criar: true, editar: true, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      necessidades_merenda: { visualizar: true, criar: true, editar: true, excluir: false },
      plano_amostragem: { visualizar: true, criar: true, editar: true, excluir: false },
      relatorio_inspecao: { visualizar: true, criar: true, editar: true, excluir: false },
      solicitacoes_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      calendario: { visualizar: true, criar: true, editar: true, excluir: false },
      formas_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      prazos_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      pedidos_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      notas_fiscais: { visualizar: true, criar: true, editar: true, excluir: false },
      pdf_templates: { visualizar: true, criar: true, editar: true, excluir: true },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    },
    III: {
      usuarios: { visualizar: false, criar: false, editar: false, excluir: false },
      fornecedores: { visualizar: false, criar: false, editar: false, excluir: false },
      clientes: { visualizar: false, criar: false, editar: false, excluir: false },
      filiais: { visualizar: false, criar: false, editar: false, excluir: false },
      centro_custo: { visualizar: false, criar: false, editar: false, excluir: false },
      almoxarifado: { visualizar: false, criar: false, editar: false, excluir: false },
      rotas: { visualizar: false, criar: false, editar: false, excluir: false },
      tipo_rota: { visualizar: false, criar: false, editar: false, excluir: false },
      produtos: { visualizar: true, criar: true, editar: true, excluir: true },
      grupos: { visualizar: true, criar: true, editar: true, excluir: true },
      subgrupos: { visualizar: true, criar: true, editar: true, excluir: true },
      classes: { visualizar: true, criar: true, editar: true, excluir: true },
      unidades: { visualizar: true, criar: true, editar: true, excluir: true },
      unidades_escolares: { visualizar: true, criar: true, editar: true, excluir: true },
      marcas: { visualizar: true, criar: true, editar: true, excluir: true },
      veiculos: { visualizar: false, criar: false, editar: false, excluir: false },
      motoristas: { visualizar: false, criar: false, editar: false, excluir: false },
      ajudantes: { visualizar: false, criar: false, editar: false, excluir: false },
      cotacao: { visualizar: true, criar: false, editar: false, excluir: false },
      produto_origem: { visualizar: true, criar: true, editar: true, excluir: true },
      produto_generico: { visualizar: true, criar: true, editar: true, excluir: true },
      intolerancias: { visualizar: true, criar: true, editar: true, excluir: true },
      patrimonios: { visualizar: false, criar: false, editar: false, excluir: false, movimentar: false },
      rotas_nutricionistas: { visualizar: true, criar: false, editar: false, excluir: false },
      tipos_cardapio: { visualizar: true, criar: false, editar: false, excluir: false },
      periodos_refeicao: { visualizar: true, criar: false, editar: false, excluir: false },
      periodicidade: { visualizar: true, criar: false, editar: false, excluir: false },
      faturamento: { visualizar: true, criar: true, editar: true, excluir: false },
      receitas: { visualizar: true, criar: true, editar: true, excluir: false },
      necessidades_merenda: { visualizar: true, criar: true, editar: true, excluir: false },
      plano_amostragem: { visualizar: true, criar: true, editar: true, excluir: false },
      relatorio_inspecao: { visualizar: true, criar: true, editar: true, excluir: false },
      solicitacoes_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      calendario: { visualizar: true, criar: true, editar: true, excluir: false },
      formas_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      prazos_pagamento: { visualizar: true, criar: true, editar: true, excluir: false },
      pedidos_compras: { visualizar: true, criar: true, editar: true, excluir: false },
      notas_fiscais: { visualizar: true, criar: true, editar: true, excluir: false },
      pdf_templates: { visualizar: true, criar: true, editar: true, excluir: true },
      permissoes: { visualizar: false, criar: false, editar: false, excluir: false }
    }
  }
};

// Lista de todas as telas disponíveis no sistema
const TODAS_TELAS = [
  'usuarios',
  'fornecedores',
  'clientes',
  'filiais',
  'centro_custo',
  'almoxarifado',
  'rotas',
  'tipo_rota',
  'produtos',
  'grupos',
  'subgrupos',
  'classes',
  'produto_origem',
  'unidades',
  'unidades_escolares',
  'marcas',
  'veiculos',
  'motoristas',
  'ajudantes',
  'cotacao',
  'produto_generico',
  'intolerancias',
  'efetivos',
  'permissoes',
  'patrimonios',
  'rotas_nutricionistas',
  'tipos_cardapio',
  'periodos_refeicao',
  'periodicidade',
  'faturamento',
  'receitas',
  'necessidades_merenda',
  'plano_amostragem',
  'relatorio_inspecao',
  'solicitacoes_compras',
  'calendario',
  'formas_pagamento',
  'prazos_pagamento',
  'pedidos_compras',
  'notas_fiscais',
  'pdf_templates'
];

// Tipos de acesso disponíveis
const TIPOS_ACESSO = [
  { valor: 'administrador', descricao: 'Administrador' },
  { valor: 'coordenador', descricao: 'Coordenador' },
  { valor: 'administrativo', descricao: 'Administrativo' },
  { valor: 'gerente', descricao: 'Gerente' },
  { valor: 'supervisor', descricao: 'Supervisor' },
  { valor: 'nutricionista', descricao: 'Nutricionista' }
];

// Níveis de acesso disponíveis
const NIVEIS_ACESSO = [
  { valor: 'I', descricao: 'Nível I - Básico' },
  { valor: 'II', descricao: 'Nível II - Intermediário' },
  { valor: 'III', descricao: 'Nível III - Avançado' }
];

// Lista de telas com descrições
const TELAS_COM_DESCRICOES = [
  { nome: 'usuarios', descricao: 'Gerenciamento de Usuários' },
  { nome: 'fornecedores', descricao: 'Gerenciamento de Fornecedores' },
  { nome: 'clientes', descricao: 'Gerenciamento de Clientes' },
  { nome: 'filiais', descricao: 'Gerenciamento de Filiais' },
  { nome: 'centro_custo', descricao: 'Gerenciamento de Centros de Custo' },
  { nome: 'almoxarifado', descricao: 'Gerenciamento de Almoxarifados' },
  { nome: 'rotas', descricao: 'Gerenciamento de Rotas' },
  { nome: 'tipo_rota', descricao: 'Gerenciamento de Tipo de Rota' },
  { nome: 'produtos', descricao: 'Gerenciamento de Produtos' },
  { nome: 'grupos', descricao: 'Gerenciamento de Grupos' },
  { nome: 'subgrupos', descricao: 'Gerenciamento de Subgrupos' },
  { nome: 'classes', descricao: 'Gerenciamento de Classes' },
  { nome: 'unidades', descricao: 'Gerenciamento de Unidades de Medida' },
  { nome: 'unidades_escolares', descricao: 'Gerenciamento de Unidades Escolares' },
  { nome: 'marcas', descricao: 'Gerenciamento de Marcas' },
  { nome: 'veiculos', descricao: 'Gerenciamento de Veículos' },
  { nome: 'motoristas', descricao: 'Gerenciamento de Motoristas' },
  { nome: 'ajudantes', descricao: 'Gerenciamento de Ajudantes' },
  { nome: 'cotacao', descricao: 'Sistema de Cotação' },
  { nome: 'produto_origem', descricao: 'Gerenciamento de Produtos Origem' },
  { nome: 'produto_generico', descricao: 'Gerenciamento de Produtos Genéricos' },
  { nome: 'intolerancias', descricao: 'Gerenciamento de Intolerâncias' },
  { nome: 'efetivos', descricao: 'Gerenciamento de Efetivos' },
  { nome: 'permissoes', descricao: 'Gerenciamento de Permissões' },
  { nome: 'patrimonios', descricao: 'Gerenciamento de Patrimônios' },
  { nome: 'rotas_nutricionistas', descricao: 'Gerenciamento de Rotas Nutricionistas' },
  { nome: 'tipos_cardapio', descricao: 'Gerenciamento de Tipos de Cardápio' },
  { nome: 'periodos_refeicao', descricao: 'Gerenciamento de Períodos de Refeição' },
  { nome: 'periodicidade', descricao: 'Gerenciamento de Periodicidade' },
  { nome: 'faturamento', descricao: 'Gerenciamento de Faturamento' },
  { nome: 'receitas', descricao: 'Gerenciamento de Receitas' },
  { nome: 'necessidades_merenda', descricao: 'Gerenciamento de Necessidades da Merenda' },
  { nome: 'plano_amostragem', descricao: 'Gerenciamento de Plano de Amostragem' },
  { nome: 'relatorio_inspecao', descricao: 'Gerenciamento de Relatórios de Inspeção de Recebimento' },
  { nome: 'solicitacoes_compras', descricao: 'Gerenciamento de Solicitações de Compras' },
  { nome: 'calendario', descricao: 'Gerenciamento de Calendário' },
  { nome: 'formas_pagamento', descricao: 'Gerenciamento de Formas de Pagamento' },
  { nome: 'prazos_pagamento', descricao: 'Gerenciamento de Prazos de Pagamento' },
  { nome: 'pedidos_compras', descricao: 'Gerenciamento de Pedidos de Compras' },
  { nome: 'notas_fiscais', descricao: 'Gerenciamento de Notas Fiscais' }
];

module.exports = {
  PERMISSOES_PADRAO,
  TODAS_TELAS,
  TIPOS_ACESSO,
  NIVEIS_ACESSO,
  TELAS_COM_DESCRICOES
};

